# Generated by Django 2.2.5 on 2019-09-29 12:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('is_ordered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('HP', 'Head phones'), ('MOB', 'Mobile'), ('TV', 'Television'), ('PCP', 'Computer Part'), ('TECH', 'Technology')], max_length=4)),
                ('product_id', models.SlugField(max_length=20, validators=[django.core.validators.RegexValidator(regex='[A-Za-z0-9]{20}$')])),
                ('previous_price', models.IntegerField(blank=True, null=True)),
                ('current_price', models.IntegerField()),
                ('is_deal_of_the_week', models.BooleanField(default=False, null=True)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('image', models.ImageField(default='product_default.jpg', upload_to='products')),
                ('label', models.CharField(blank=True, choices=[('BS', 'Best Seller'), ('N', 'New'), ('OFS', 'Out of stock'), ('C', 'Our Choice'), ('F', 'Featured'), ('OS', 'On Sale')], max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='20 A-Z a-z 0-9', regex='[a-zA-Z0-9]{20}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('is_being_processed', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_recieved', models.BooleanField(default=False)),
                ('refund_requested', models.BooleanField(default=False)),
                ('refund_granted', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='core.CartItem')),
                ('reference_code', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_code', to='core.ReferenceCode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
    ]
