# Generated by Django 2.2.5 on 2019-09-30 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('HP', 'Headphones'), ('MOB', 'Mobile'), ('TV', 'Television'), ('PCP', 'Computer Part'), ('TECH', 'Technology')], max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.SlugField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(regex='[A-Za-z0-9]{20}$')]),
        ),
    ]
