# Generated by Django 2.2.5 on 2019-09-30 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190930_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='dummy text dummy text dummy text dummy text dummy text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.SlugField(blank=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(regex='[A-Za-z0-9]{20}$')]),
        ),
    ]
