# Generated by Django 2.2.5 on 2019-09-30 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190930_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.SlugField(blank=True, max_length=80, unique=True, validators=[django.core.validators.RegexValidator(regex='[A-Za-z0-9]{20}$')]),
        ),
    ]
